#pragma once
#include "ECSFrame/SystemUtils.h"
#include "ECSFrame/Model/System/ISystem.h"
#include "ECSFrame/Model/Component/IComponent.h"
#include "ECSFrame/Model/Entity/IEntity.h"
#include "ECSFrame/Query/IQuery.h"
#include "ECSFrame/Query/QueryPreset.h"
#include "ECSFrame/Global/GlobalPool.h"
#include "ECSFrame/Global/GlobalQuery.h"